### ISSUE TITLE
[NOT ISSUE] New mod suggestion about teleportstone

### ISSUE THREAD

**Issue by dhon-ee** [antiftw/gyk-nkn-fix#1]
First of all thanks for the fix.

I would like to see a mod where I can quickly teleport to sweat home, quarry etc using shortcut key. like numpad buttons [1, 2, 3] without having to open inventory and click the teleport stone and choose location

Is it possible to make it or can you give any idea how to make such one. I have 0 experience modding games

Again Thanks for the wonderful fix of this mod.

**Comment by dhon-ee** [comment]
Just figured out how to do it

**Comment by atjsd** [comment]
Ok nice, sounds like useful functionality! Got a link to the mod? ;)

**Comment by atjsd** [comment]
> Again Thanks for the wonderful fix of this mod.
You're welcome

>Again Thanks for the wonderful fix of this mod.
Glad you were able to figure it oud. To be honest I wouldn't have had a clue, since I am also not really experienced writing mods. :)

**Comment by antiftw** [comment]
> Again Thanks for the wonderful fix of this mod.

You're welcome

>Just figured out how to do it

Glad you were able to figure it out. To be honest I wouldn't have had a clue, since I am also not really experienced writing mods. :)

**Comment by mdn522** [comment]
Had to look through codes inside `Assembly-CSharp.dll` and dump GD points

Link to the mod: https://github.com/mdn522/GYK-TeleportHotkey

Known bugs:
* Teleporting inside building from outside causes visual bug (most of the time. not sure why). not game-breaking though

*This repository uses `antiftw/gyk-nkn-fix` as boilerplate

**Comment by antiftw** [comment]
Cool, thanks for sharing the repo!
